services:

  #controllers
  authcontroller:
    image: ${DOCKER_REGISTRY-}authcontroller
    build:
      context: .
      dockerfile: Auth/AuthController/Dockerfile
    environment:
      - DB_CONNECTION=Server=db; Database=Auth; User Id=sa; Password=YourStrong!Passw0rd; Encrypt=True; TrustServerCertificate=True;
      - JWT_KEY=rpK3dMglgZgsosi9uFEfPbpPdukhIbiP
      - ADMIN_NAME=admin
      - ADMIN_EMAIL=admin@adminMail.by
      - ADMIN_PASSWORD=h1gHLyS3curedP4ssW0rd
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - SMTP_USER=name
      - SMTP_PASS=pass
    depends_on:
      - db
      - rabbitmq
    ports:
      - 5001:8080
      - 5101:8081
    volumes:
      - db_data:/var/lib/sqlserver

  profilescontroller:
    image: ${DOCKER_REGISTRY-}profilescontroller
    build:
      context: .
      dockerfile: Profiles/ProfilesController/Dockerfile
    environment:
      - DB_CONNECTION=Server=db; Database=Profiles; User Id=sa; Password=YourStrong!Passw0rd; Encrypt=True; TrustServerCertificate=True;
      - JWT_KEY=rpK3dMglgZgsosi9uFEfPbpPdukhIbiP
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - db
      - rabbitmq
    ports:
      - 5002:8080
      - 5102:8081
    volumes:
      - db_data:/var/lib/sqlserver
  
  officescontroller:
    image: ${DOCKER_REGISTRY-}officescontroller
    build:
      context: .
      dockerfile: Offices/OfficesController/Dockerfile
    environment:
      - DB_CONNECTION=Server=db; Database=Offices; User Id=sa; Password=YourStrong!Passw0rd; Encrypt=True; TrustServerCertificate=True;
      - JWT_KEY=rpK3dMglgZgsosi9uFEfPbpPdukhIbiP
    depends_on:
      - db
    ports:
      - 5003:8080
      - 5103:8081
    volumes:
      - db_data:/var/lib/sqlserver

  documentscontroller:
    image: ${DOCKER_REGISTRY-}documentscontroller
    build:
      context: .
      dockerfile: Documents/DocumentsController/Dockerfile
    environment:
      - BLOB_CONN_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
      - JWT_KEY=rpK3dMglgZgsosi9uFEfPbpPdukhIbiP
      - MONGODB_URI=mongodb://root:example@mongo:27017/
      - DB_NAME=DocumentsDb
    depends_on:
      - mongo
      - azurite
    ports:
      - 5004:8080
      - 5104:8081
    volumes:
      - mongo_data:/var/lib/mongo_db
      - azure_data:/var/lib/azure_blob

  #persistence
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/lib/sqlserver
 
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  #RabbitMq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  #Azure BLOB storage
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    
volumes:
  rabbitmq_data:
  db_data:  
  mongo_data:  
  azure_data:
